language: bash
sudo: require
dist: trusty

before_script:

  - mkdir $HOME/Downloads
  - export PANDOCVERS=2.1.1-linux
  - wget https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-$PANDOCVERS.tar.gz -O $HOME/Downloads/pandoc.tar.gz
  - export TGZ=$HOME/Downloads/pandoc.tar.gz
    #- mkdir $HOME/.local     # File already exists
  - export DEST=$HOME/.local
  - tar xvzf $TGZ --strip-components 1 -C $DEST
  - export PATH=$HOME/.local/bin:$PATH
  - export PREFIX=./AppImage-manpages
  - mkdir -p $PREFIX/{man,pdf,epub,html}
  - export MANDIR=$PREFIX/man
  - export PDFDIR=$PREFIX/pdf
  - export EPUBDIR=$PREFIX/epub
  - export HTMLDIR=$PREFIX/html
  - export VERSION=0.0.1
  - export DATE=$(/bin/date "+%Y-%m-%d")
  - find $HOME/.local -type f -ls        # For debugging only
  - find $PREFIX      -type d -ls        # For debugging only

script:

  - cd markdown
  - ls -l *.md
  
  - # Manual pages:
  - for i in *.md ; do cat $i | sed 's#__date__#'"$DATE"'#' | pandoc -s -t man   -f markdown -o $MANDIR/${i/-manpage.md/.man} -V footer:"Manual Page Version $VERSION, $DATE" ; done
  
  - # HTML docs:
  - for i in *.md ; do cat $i | sed 's#__date__#'"$DATE"'#' | pandoc -s -t html  -f markdown -o $HTMLDIR/${i/-manpage.md/.html} ; done
  
  - # PDF docs:
  - for i in *.md ; do cat $i | sed 's#__date__#'"$DATE"'#' | pandoc -s -t latex -f markdown -o $PDFDIR/${i/-manpage.md/.pdf} -V geometry:"margin=1.5cm, paperwidth=595pt, paperheight=297mm" ; done
  
  - # EPUB docs:
  - for i in *.md ; do cat $i | sed 's#__date__#'"$DATE"'#' | pandoc -s -t epub3 -f markdown -o $EPUBDIR/${i/-manpage.md/.epub} ; done
  
  - # Make tarball:
  - cd ..
  - export TARBALL=AppImage-manpages-$TRAVIS_BUILD_NUMBER-git.$(git rev-parse --short HEAD)-$DATE.tar.gz
  - tar cvzf $TARBALL.tar.gz $PREFIX
  
  - # Upload results:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./TARBALL.tar.gz
